### ISSUE TITLE
NoSuchAccountError after upgrading

### ISSUE THREAD

**Issue by nexusVI** [mautrix/signal#215]
After upgrading to the most recent version, mautrix-signal doesn't start anymore. 

```
[2022-02-05 20:34:13,540] [INFO@mausignald] Connected to signald v0.14.0-58-93ee329a
[2022-02-05 20:34:13,605] [CRITICAL@mau.init] Unexpected error in main event loop
Traceback (most recent call last):
  File "/usr/local/mautrix-signal/lib/python3.9/site-packages/mautrix/util/program.py", line 219, in _run
    self.loop.run_until_complete(self.start())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/mautrix-signal/lib/python3.9/site-packages/mautrix_signal/__main__.py", line 74, in start
    await super().start()
  File "/usr/local/mautrix-signal/lib/python3.9/site-packages/mautrix/bridge/bridge.py", line 196, in start
    await super().start()
  File "/usr/local/mautrix-signal/lib/python3.9/site-packages/mautrix/util/program.py", line 252, in start
    await asyncio.gather(*(self.startup_actions or []))
  File "/usr/local/mautrix-signal/lib/python3.9/site-packages/mautrix_signal/signal.py", line 231, in start
    if await self.subscribe(user.username):
  File "/usr/local/mautrix-signal/lib/python3.9/site-packages/mausignald/signald.py", line 98, in subscribe
    await self.request_v1("subscribe", account=username)
  File "/usr/local/mautrix-signal/lib/python3.9/site-packages/mausignald/rpc.py", line 231, in request_v1
    return await self._request(command, expected_response=command, version="v1", **data)
  File "/usr/local/mautrix-signal/lib/python3.9/site-packages/mausignald/rpc.py", line 225, in _request
    resp_type, resp_data = await self._raw_request(command, **data)
  File "/usr/local/mautrix-signal/lib/python3.9/site-packages/mausignald/rpc.py", line 222, in _raw_request
    return await asyncio.shield(future)
mausignald.errors.ResponseError: NoSuchAccountError: account not found
```

How can I fix this startup error? 

Regards

**Comment by nexusVI** [comment]
It was a problem in the config file, looking at this diff between config.yaml and example-config.yaml it was fixed easily. 

```
253,262c240,244
<             m.file: '$sender_displayname sent a file'
<             m.image: '$sender_displayname sent an image'
<             m.audio: '$sender_displayname sent an audio file'
<             m.video: '$sender_displayname sent a video'
<             m.location: '$sender_displayname sent a location'
---
>             m.file: $sender_displayname sent a file
>             m.image: $sender_displayname  sent an image
>             m.audio: $sender_displayname  sent an audio file
>             m.video: $sender_displayname  sent a video
>             m.location: $sender_displayname  sent a location
```

**Comment by tulir** [comment]
The bridge previously had a bug where subscribe errors weren't caught properly (which is already fixed on master), but the source of the issue is that some signald data was removed without telling the bridge. You can remove the corresponding `username` and `uuid` fields in the `user` table, or relogin to signald with the same phone number. Also, that signald version looks outdated.

**Comment by nexusVI** [comment]
My `user` table looks like this:
```
signal=# select * from user;
   user   
----------
 postgres
(1 row)
```

I updated signald and performed a new registration, but am still getting the same error on mautrix-signal startup.

**Comment by sumnerevans** [comment]
That's the wrong `user` table. You need:

```
mautrix_signal=> select * from "user";
       mxid        |   username   |                 uuid                 | notice_room
-------------------+--------------+--------------------------------------+-------------
 @sumner:localhost | +17203067357 | 7e6f58a7-5137-499c-a000-e0af38a23af8 |
(1 row)
```
