### ISSUE TITLE
User exits room after creating their own signalbot bridge

### ISSUE THREAD

**Issue by ReggieMarr** [mautrix/signal#44]
I found that if I am messaging a user which also is using the signalbot that they "leave the room" and I cannot get messages through to them. (Although I can receive messages).

Additionally if I try to recreate a room (or private messages) via the signal bot I get the following:

```
reggiemarr 
pm [phone number]
Signal bridge bot
You already have a private chat with [phone number] (Signal): !CjMNvQkJloeraNWxgf:bridge.monster

Unhandled error while handling command. Check logs for more details (ref: 1611502792).
```

When I go to check the logs I find the following:
```
root@localhost:~# journalctl -fu matrix-mautrix-signal
-- Logs begin at Sat 2021-01-23 16:58:56 UTC. --
Jan 24 16:53:57 localhost matrix-mautrix-signal[12611]:     resp = await self.request("register", "verification_required", username=phone,
Jan 24 16:53:57 localhost matrix-mautrix-signal[12611]:   File "/opt/mautrix-signal/mausignald/rpc.py", line 198, in request
Jan 24 16:53:57 localhost matrix-mautrix-signal[12611]:     resp_type, resp_data = await self._raw_request(command, **data)
Jan 24 16:53:57 localhost matrix-mautrix-signal[12611]:   File "/opt/mautrix-signal/mausignald/rpc.py", line 195, in _raw_request
Jan 24 16:53:57 localhost matrix-mautrix-signal[12611]:     return await future
Jan 24 16:53:57 localhost matrix-mautrix-signal[12611]: mausignald.errors.UnexpectedError: Bad response: 400
Jan 24 16:53:57 localhost matrix-mautrix-signal[12611]: [2021-01-24 16:53:57,876] [INFO@aiohttp.access] 172.18.0.4 [24/Jan/2021:16:53:57 +0000] "PUT /transactions/233?access_token=9c30f6b3-d0a7-541c-a6a2-e48dd2762827 HTTP/1.1" 200 158 "-" "Synapse/1.25.0"
Jan 24 16:54:32 localhost matrix-mautrix-signal[12611]: [2021-01-24 16:54:32,512] [DEBUG@mau.mx] Received Matrix event $ynHpaXTlD-mJPAxaECBfQ64liGff9TJqAuNoAiz0cqM from @reggiemarr:bridge.monster in !gdxCwyEIgQzISNPftq:bridge.monster
Jan 24 16:54:32 localhost matrix-mautrix-signal[12611]: [2021-01-24 16:54:32,513] [INFO@aiohttp.access] 172.18.0.4 [24/Jan/2021:16:54:32 +0000] "PUT /transactions/234?access_token=9c30f6b3-d0a7-541c-a6a2-e48dd2762827 HTTP/1.1" 200 158 "-" "Synapse/1.25.0"
Jan 24 16:54:32 localhost matrix-mautrix-signal[12611]: [2021-01-24 16:54:32,612] [INFO@aiohttp.access] 172.18.0.4 [24/Jan/2021:16:54:32 +0000] "PUT /transactions/235?access_token=9c30f6b3-d0a7-541c-a6a2-e48dd2762827 HTTP/1.1" 200 158 "-" "Synapse/1.25.0"
Jan 24 17:00:08 localhost matrix-mautrix-signal[12611]: [2021-01-24 17:00:08,391] [DEBUG@mau.mx] Received Matrix event $3BMeyBMwJoaEJXvI0LRYexH0SBMxKRuVRp1PAZXObLQ from @reggiemarr:bridge.monster in !gdxCwyEIgQzISNPftq:bridge.monster
Jan 24 17:00:08 localhost matrix-mautrix-signal[12611]: [2021-01-24 17:00:08,393] [INFO@aiohttp.access] 172.18.0.4 [24/Jan/2021:17:00:08 +0000] "PUT /transactions/236?access_token=9c30f6b3-d0a7-541c-a6a2-e48dd2762827 HTTP/1.1" 200 158 "-" "Synapse/1.25.0"
Jan 24 17:00:08 localhost matrix-mautrix-signal[12611]: [2021-01-24 17:00:08,880] [INFO@aiohttp.access] 172.18.0.4 [24/Jan/2021:17:00:08 +0000] "PUT /transactions/237?access_token=9c30f6b3-d0a7-541c-a6a2-e48dd2762827 HTTP/1.1" 200 158 "-" "Synapse/1.25.0"
Jan 24 17:00:08 localhost matrix-mautrix-signal[12611]: [2021-01-24 17:00:08,900] [ERROR@mau.commands] Unhandled error while handling command pm [phone number] from @reggiemarr:bridge.monster (ref: 1611502792)
Jan 24 17:00:08 localhost matrix-mautrix-signal[12611]: Traceback (most recent call last):
Jan 24 17:00:08 localhost matrix-mautrix-signal[12611]:   File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 329, in ensure_joined
Jan 24 17:00:08 localhost matrix-mautrix-signal[12611]:     await self.join_room(room_id, max_retries=0)
Jan 24 17:00:08 localhost matrix-mautrix-signal[12611]:   File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 83, in wrapper
Jan 24 17:00:08 localhost matrix-mautrix-signal[12611]:     return await __method(*args, **kwargs)
Jan 24 17:00:08 localhost matrix-mautrix-signal[12611]:   File "/usr/lib/python3.8/site-packages/mautrix/client/api/rooms.py", line 252, in join_roomJan 24 17:00:08 localhost matrix-mautrix-signal[12611]:     content = await self.api.request(Method.POST, Path.join[room_id_or_alias],
Jan 24 17:00:08 localhost matrix-mautrix-signal[12611]:   File "/usr/lib/python3.8/site-packages/mautrix/api.py", line 233, in request
Jan 24 17:00:08 localhost matrix-mautrix-signal[12611]:     return await self._send(method, full_url, content, query_params, headers or {})
Jan 24 17:00:08 localhost matrix-mautrix-signal[12611]:   File "/usr/lib/python3.8/site-packages/mautrix/api.py", line 158, in _send
Jan 24 17:00:08 localhost matrix-mautrix-signal[12611]:     raise make_request_error(http_status=response.status,
Jan 24 17:00:08 localhost matrix-mautrix-signal[12611]: mautrix.errors.request.MUnknown: No known servers
Jan 24 17:00:08 localhost matrix-mautrix-signal[12611]: The above exception was the direct cause of the following exception:
Jan 24 17:00:08 localhost matrix-mautrix-signal[12611]: Traceback (most recent call last):
Jan 24 17:00:08 localhost matrix-mautrix-signal[12611]:   File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 405, in handle
Jan 24 17:00:08 localhost matrix-mautrix-signal[12611]:     await self._run_handler(handler, evt)
Jan 24 17:00:08 localhost matrix-mautrix-signal[12611]:   File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 290, in __call__
Jan 24 17:00:08 localhost matrix-mautrix-signal[12611]:     return await self._handler(evt)
Jan 24 17:00:08 localhost matrix-mautrix-signal[12611]:   File "/usr/lib/python3.8/site-packages/mautrix_signal/commands/signal.py", line 75, in pm
Jan 24 17:00:08 localhost matrix-mautrix-signal[12611]:     await portal.main_intent.invite_user(portal.mxid, evt.sender.mxid)
Jan 24 17:00:08 localhost matrix-mautrix-signal[12611]:   File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 94, in wrapper
Jan 24 17:00:08 localhost matrix-mautrix-signal[12611]:     await __self.ensure_joined(room_id)
Jan 24 17:00:08 localhost matrix-mautrix-signal[12611]:   File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 351, in ensure_joined
Jan 24 17:00:08 localhost matrix-mautrix-signal[12611]:     raise IntentError(f"Failed to join room {room_id} as {self.mxid}") from e
Jan 24 17:00:08 localhost matrix-mautrix-signal[12611]: mautrix.errors.base.IntentError: Failed to join room !CjMNvQkJloeraNWxgf:bridge.monster as @signal_4ac31767-acc8-4219-829c-249b7a1c6587:bridge.monster
Jan 24 17:00:08 localhost matrix-mautrix-signal[12611]: [2021-01-24 17:00:08,984] [INFO@aiohttp.access] 172.18.0.4 [24/Jan/2021:17:00:08 +0000] "PUT /transactions/238?access_token=9c30f6b3-d0a7-541c-a6a2-e48dd2762827 HTTP/1.1" 200 158 "-" "Synapse/1.25.0"

```

I tried looking around commands/signal.py saw there were some recent changes to contact synchronization and such. Anything of note that I could test out ? Or is this something that's expected as things are changing around?

Also I've setup my server using the ansible docker playbook if that matters.

**Comment by buxel** [comment]
I have exactly the same issue. I was testing the bridge with a friend and after some configuration changes and re-deployment i i could talk to everyone but him. 

I tried joining the room using the ID shown in the error message but this results in "Failed to join room - No known servers". So either i have to delete this "invisible" room somehow or convince the bridge to open a new one for this contact.

Any ideas?

**Comment by ReggieMarr** [comment]
@buxel are you using [this ansible playbook?](https://github.com/spantaleev/matrix-docker-ansible-deploy) I'm wondering if I were to wipe clean my postgres db and restart the homeserver clean if that'd fix things. Although it seems like I would just run into the same problem again.

**Comment by buxel** [comment]
@ReggieMarr yes, indeed. I forgot to mention that I was using this playbook.

For me, a temporary workaround wich alows me to use the bridge for myself would be great. Like manually deleting broken rooms somehow. I expected the `cleanup-rooms` command to help here but it also misses the broken one.

In the long run i'd like to offer usign the bridge to some friends to get them interested in matrix. This is when I'd run into this issue again i guess.

**Comment by ReggieMarr** [comment]
@buxel a temporary work around I've been using is just creating a signal group with myself and the user I normally can't talk to. After I've created it on signal I seem to be able to use it in the bridge just fine.
this is a bit of a hack and I'd still like to fix whatevers going wrong but at least it makes things usable

**Comment by ReggieMarr** [comment]
@buxel a temporary work around I've been using is just creating a signal group with myself and the user I normally can't talk to. After I've created it on signal I seem to be able to use it in the bridge just fine.
this is a bit of a hack and I'd still like to fix whatevers going wrong but at least it makes things usable

> @ReggieMarr yes, indeed. I forgot to mention that I was using this playbook.
> 
> For me, a temporary workaround wich alows me to use the bridge for myself would be great. Like manually deleting broken rooms somehow. I expected the `cleanup-rooms` command to help here but it also misses the broken one.
> 
> In the long run i'd like to offer usign the bridge to some friends to get them interested in matrix. This is when I'd run into this issue again i guess.

@buxel a temporary work around I've been using is just creating a signal group with myself and the user I normally can't talk to. After I've created it on signal I seem to be able to use it in the bridge just fine.
this is a bit of a hack and I'd still like to fix whatevers going wrong but at least it makes things usable

**Comment by buxel** [comment]
@ReggieMarr thanks for the tip! i can confirm this workaround works for me, too.

**Comment by Bergruebe** [comment]
I have the same error/bug, thanks for your tips!

**Comment by Evidlo** [comment]
Maybe there is a postgres command we could use to clear the database and fix this?

**Comment by Evidlo** [comment]
Also, I can't see how the above workaround can work when you've registered the bridge as a primary device.

**Comment by sboeckelmann** [comment]
Well this issue still seems to exist. I hope someone will take care of in some time ;-)
Anyway, I was able to re-initial my private signal chat in matrix with the user that dropped out after linking their own signal user to their matrix user.

This is what I have done:
identified the room that's failing from error log(s)
`mautrix.errors.base.IntentError: Failed to join room !abc:example.com as @signal_xyz:example.com`

I was hoping that mautrix signal might recover if that room was deleted, so used the admin api:
`
DELETE /_synapse/admin/v1/rooms/%21abc%3Aexample.com
  { "purge": true }
`

but that issue still existed - the room id must still be sitting somewhere in mautrx_signal database, so it did.
`
delete from mx_user_profile where room_id = '!abc@examle.com';
delete from mx_room_state where room_id = '!abc@examle.com';
delete from message  where mx_room = '!abc@examle.com';
delete from portal where mxid = '!abc@examle.com';
`
After deleting all references I was able to re-invite that signal user by using the **pm** command.
The last one, **delete from portal**, seemed to have finally done the trick.

Hope this helps others to resolve similar issues as long as the root cause in mautrix signal has not been taken of.

**Comment by Liarra** [comment]
Any particular reason why it is closed? I just had the same issue at 0.2.3. @sboeckelmann 's workaround has worked for me, but I can't imagine having to do this each time I drag another buddy from Signal onto Matrix.

**Comment by tulir** [comment]
Oops, I thought it was one of the issues where people had messed with the portals themselves. Anyway, it's fixed now.

**Comment by sboeckelmann** [comment]
@tulir : cool, thank you for the fix!
can you please provide the commit id of the fix? Then we can monitor ourseveles in which version we can expect it to be working ;-)
Thanks!

**Comment by jswetzen** [comment]
I got the same error with a newly installed signal bridge (with the same ansible playbook) after experimenting a lot with adding and removing a user to some different rooms. So this issue still exists, but I don't have a clear case for reproducing it.
